env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides:
  - files: ["*.yaml", "*.yml"]
    plugins: ["yaml"]
    extends: ["plugin:yaml/recommended"]
# Required when using experimental EcmaScript features
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  # Options specific to the Babel parser
  requireConfigFile: false
  babelOptions:
    plugins:
    - "@babel/plugin-syntax-import-assertions"
rules: {}
globals:
  it: readonly
  describe: readonly
  process: readonly
  __dirname: readonly

