Unreleased:
  date:
  Added:
  Changes:
  Deprecated:
  Fixed:
  Removed:
  Security:

2.5.0:
  date: 2020-04-05
  Added:
    diana:
      - Diana is a top with a draped neck
    i18n:
      - title, description, and options for Dianna
  Changes:
    css-theme:
      - The sidebar no longer has a different background
  Fixed:
    css-theme:
      - Fixed incorrect border value on active sidebar link

2.4.6:
  date: 2020-03-23
  Fixed:
    i18n:
      - Fixed an bug in the i18n package

2.4.5:
  date: 2020-03-19
  Changes:
    fu:
      - Improved shape based on community feedback
    utils:
      - neckstimate() now returns values rounded to nearest mm
  Fixed:
    wahid:
      - Check whether frontScyeDart option is zero prior to implementing it

2.4.4:
  date: 2020-03-15
  Changes:
    plugin-dimension:
      - Don't escape inch symbol in text. Instead let Svg.escapeText() handle it at render time
  Fixed:
    core:
      - New Svg.escapeText() method to escape text at render time, rather than at draft time
        This fixes the difference in the inch symbol is displayed in the React component or rendered SVG
    huey:
      - The `sleevecapBackFactorY` and `sleevecapFrontFactorY` options had a minimum above the default
    simon:
      - The `sleevecapBackFactorY` and `sleevecapFrontFactorY` options had a minimum above the default
    simone:
      - The `sleevecapBackFactorY` and `sleevecapFrontFactorY` options had a minimum above the default
    sven:
      - The `sleevecapBackFactorY` and `sleevecapFrontFactorY` options had a minimum above the default

2.4.3:
  date: 2020-03-12
  Added:
    i18n:
      - Added more translations

2.4.2:
  date: 2020-03-08
  Added:
    i18n:
      - Added more strings
  Changed:
    components:
      - Don't load docs in DraftConfigurator
    plugin-title:
      - Added *for* to title output

2.4.1:
  date: 2020-03-04
  Fixed:
    components:
      - Fixed `updatePatternData` props issue in the Workbench component
    utils:
      - "[#542](https://github.com/freesewing/freesewing.org/issues/542):
        Prevent neckstimate from throwing when getting an unexpected measurement "

2.4.0:
  date: 2020-02-29
  Added:
    fu:
      - Fu is a face mask pattern

2.3.0:
  date: 2020-02-23
  Added:
    holmes:
      - Homes is a pattern for a Sherlock Holmes hat
    plugin-gore:
      - A plugin to generate gores for semi-spheres or domes

2.2.0:
  date: 2020-02-22
  Added:
    breanna:
      - Breanna is a body block for womenswear
    css-theme:
      - Added styling for table.data
    components:
      - Added LineDrawing for Breanna
    core:
      - Added the `Path.noop()` method
      - Added the `Path.insop()` methods
    i18n:
      - Added translations for Breanna
  Changed:
    aaron:
      - Removed deprecated `centerBackNeckToWaist` measurement
    bent:
      - Removed deprecated `centerBackNeckToWaist` measurement
    breanna:
      - Removed deprecated `centerBackNeckToWaist` and `hpsToWaistBack` measurements
    brian:
      - Reworked Brian to use the new shoulderslope measurement
      - Removed deprecated `centerBackNeckToWaist` measurement
      - The `neck` point has been renamed to `hps`
    carlton:
      - Removed deprecated `centerBackNeckToWaist` measurement
    carlita:
      - Renamed `highPointShoulderToBust` measurement to `hpsToBust`
      - Removed deprecated `centerBackNeckToWaist` measurement
    components:
      - DraftConfigurator has been updated to reflect frontend naming changes
      - Updated Workbench component to pass data rather than gist to DraftConfigurator
      - Term `pattern` is now `design`
      - Term `recipe` is now `pattern`
      - Term `gist` is now `data`
    css-theme:
      - Added new styles for the frontend changes in 2.2
      - Removed smaller fonts in ul.links
    i18n:
      - Added/Updated strings for the 2.2 frontend changes
      - Changed `Joost De Cock` to `Joost` because spam filters don't like cock
    models:
      - Extended the menswear size range to have 10 different sizes, just like womenswear
    mui-theme:
      - Changed the light background to `#f8f9fa` rather than `#fff`
      - Changed the navbar to be light/dark based on the theme, rather than always dark
    huey:
      - Removed deprecated `centerBackNeckToWaist` measurement
    hugo:
      - Removed deprecated `centerBackNeckToWaist` measurement
    jaeger:
      - Removed deprecated `centerBackNeckToWaist` measurement
    simon:
      - Removed deprecated `centerBackNeckToWaist` measurement
    simone:
      - Renamed `highPointShoulderToBust` measurement to `hpsToBust`
      - Removed deprecated `centerBackNeckToWaist` measurement
    sven:
      - Removed deprecated `centerBackNeckToWaist` measurement
    utils:
      - Neckstimate now uses proportions only
    tamiko:
      - Removed deprecated `centerBackNeckToWaist` measurement
    trayvon:
      - Removed deprecated `centerBackNeckToWaist` measurement
    wahid:
      - Removed deprecated `centerBackNeckToWaist` measurement
  Removed:
    i18n:
      - Removed the files for homepage translation, and moved that content to markdown
      - Removed the files for editor translation, as it is no longer used
  Fixed:
    create-freesewing-pattern:
      - "[#257](https://github.com/freesewing/freesewing/issues/257):
        Explain that pattern names are bound by the constraints of NPM package names"
    hugo:
      - Made sure dimensions for hood center and waistband are always shown
    florent:
      - Fixed an SA issue in brim top and removed SA from interfacing
    sandy:
      - Fixed tags in pattern config file
    theo:
      - Fixed issue with side piece
    penelope:
      - Fixed tags in pattern config file
    waralee:
      - Fixed tags in pattern config file

2.1.9:
  date: 2020-01-18
  Fixed:
    simon:
      - "[#253](https://github.com/freesewing/freesewing/issues/253):
        Fixed type in simon sleeve causing incorrect cuff issue"
    core:
      - "[#19](https://github.com/freesewing/freesewing/issues/19):
        Path offset issue is now fixed in upstream bezier-js@2.4.6"

2.1.8:
  date: 2019-12-16
  Fixed:
    simon:
      - "[#416](https://github.com/freesewing/freesewing.org/issues/416):
        Fixed bug in simon sleeve"

2.1.7:
  date: 2019-12-15
  Fixed:
    carlton:
      - Added missing scalebox
      - Re-numbered tail as part 5

2.1.6:
  date: 2019-11-24
  Fixed:
    utils:
      - "[#317](https://github.com/freesewing/freesewing.org/issues/317):
        Fixed bug where format was not passed to formatImperial"

2.1.5:
  date: 2019-11-19
  Fixed:
    plugin-dimension:
      - Fixed issue where inch marks where breaking SVG because of unescaped double quotes

2.1.4:
  date: 2019-11-01
  Added:
    css-theme:
      - Added styling for search results
  Changed:
    components:
      - Footer version number now links to Github release page
    example:
      - Added the `snap-male` and `snap-female` snippets to the `plugin-buttons` example
  Deprecated:
    components:
      - The Draft component has been renamed to Render. Draft still works, but will be removed in a future release.
  Removed:
    components:
      - The Ogol component has been removed as it wasn't used
  Fixed:
  Security:

2.1.3:
  date: 2019-10-18
  Added:
    i18n:
      - More translated strings
  Changed:
    utils:
      - Adjusted slope of the shoulderToShoulder measurement in neckstimate data
  Fixed:
    utils:
      - "[#250](https://github.com/freesewing/freesewing.org/issues/250):
        Model page stays empty with pre 2.0 model data: Error: 'neckstimate() requires a valid measurement name as second parameter. (received underBust)'"

2.1.2:
  date: 2019-10-14
  Fixed:
    i18n:
      - Fixed issue where symlinks were causing all languages to export English strings

2.1.1:
  date: 2019-10-13
  Added:
    components:
      - Added the fixme type Blockquote component
    gatsby-remark-jargon:
      - Added the gatsby-remark-jargon package, a gatbsy plugin wrapping remark-jargon
    remark-jargon:
      - Added the remark-jargon package, a remark plugin for jargon terms
  Fixed:
    css-theme:
      - Fixed padding issue on mobile
    utils:
      - Fixed an issue with the formatMm method not adding units

2.1.0:
  date: 2019-10-06
  Added:
    components:
      - Added support for restoring recipe and pattern defaults in DraftConfigurator
    i18n:
      - Added translations for Penelope, Waralee, and Simone
    simone:
      - Added the Simone shirt pattern
    penelope:
      - Added the Penelope Pencil Skirt pattern by @woutervdub
    utils:
      - Added backend methods for administration
      - Added the resendActivationEmail method to backend
    waralee:
      - Added the Waralee wrap Pants pattern by @woutervdub
  Changed:
    css-theme:
      - Made tweaks to the main/sidebar layout
    core:
      - The pattern super constructor now sets a `config` property that
        holds the pattern configuration. This means that unlike before, there
        is no need to instantiate a pattern to access its config. You can just
        import the pattern, and it's config property will contain the pattern config.
    components:
      - Added Penelope and Waralee linedrawings
      - Changed animation of the Spinner component
    simon:
      - "[#123](https://github.com/freesewing/freesewing/issues/123):
        Added a box pleat option to Simon"
      - Added the `backDarts` option to control the inclusion of back darts
      - Added the `backDartsShaping` option to control the amount of shaping by the back darts
      - Changed the defaults to slightly reduce the ease and adapt the sleevecap

  Deprecated:
    patterns:
      - The [@freesewing/patterns](https://www.npmjs.com/package/@freesewing/patterns)
        package has been deprecated. Please import our patterns individually.
  Fixed:
    components:
      - Fixed display of nested option in SampleConfigurator
      - Fixed conflicting key values in React components
      - Fixed issue with display of list options in Draftconfigurator
    css-theme:
      - Reduced the sidebar height by 64px to take navbar into account
      - Fixed blockquote width on XS screens
      - Made sidebar wider
    simon:
      - Fixed an issue where the store wasn't properly initialized causing hips and waist ease
        to be set incorrectly
      - Added a missing paperless dimension for the waist
      - Fixed an issue where the split yoke option was not taken into account correctly
    utils:
      - Fixed an issue where optionDefault was not handling list options correctly

2.0.4:
  date: 2019-09-27
  Added:
    components:
      - Advanced options and settings are now hidden by default in DraftConfigurator
  Fixed:
    carlton:
      - "[#108](https://github.com/freesewing/freesewing/issues/108):
        Fixed incorrect width of the Carlton tail"
    components:
      - "[#104](https://github.com/freesewing/freesewing/issues/104):
        Fixed incorrect embed setting on Workbench pattern export"

2.0.3:
  date: 2019-09-15
  Changed:
    components:
      - Tweaked DraftConfigurator tags to match CSS rules after frontend upgrade to react-intl v3
  Fixed:
    bruce:
      - "[#106](https://github.com/freesewing/freesewing/issues/106):
        Fix incorrect hem allowance"
    create-freesewing-pattern:
      - Updated example package.json to use latest tag rather than beta
    utils:
      - Fix measurementDiffers to pass breasts parameter to neckstimate

2.0.2:
  date: 2019-09-06
  Added:
    i18n:
      - "[#90](https://github.com/freesewing/freesewing/issues/90):
        Added missing option translations for Benjamin, Florent, Sandy, Shin, and Theo"
  Changed:
    create-freesewing-pattern:
      - Updated dependencies
  Fixed:
    benjamin:
      - Added bandLength option to fit optiongroup (it was missing)
    css-theme:
      - Updated styles for DraftConfigurator component for pattern options 3 levels deep
    components:
      - "[#104](https://github.com/freesewing/freesewing.org/issues/104):
        Changed `onDragEnd` to `onChangeCommitted` in slider element
        (change in material-ui API when slider came out of beta)"
      - Workbench now also lets you preload a `withBreasts` set of measurements
      - DraftConfigurator now properly styles pattern options 3 levels deep
      - "[#105](https://github.com/freesewing/freesewing.org/issues/105):
        Moved state change in render loop to useEffect"
    create-freesewing-pattern:
      - Added missing `file-saver` dependency
    jaeger:
      - "[#76](https://github.com/freesewing/freesewing.org/issues/76):
        Fixed a typo in Jaeger that was causing the side vent length to be wrong"
    simon:
      - "[#100](https://github.com/freesewing/freesewing.org/issues/100):
        Updated simon with more sensible defaults for ease options"
      - "[#102](https://github.com/freesewing/freesewing.org/issues/102):
        Fixed 'Snippets not defined' error when drafting a seperate button placket"
      - "[#103](https://github.com/freesewing/freesewing.org/issues/103):
        Fixed 'hemSa not defined' when drafting paperless Simon without seam allowance"
    utils:
      - Removed lingering debug statement in formatImperial

2.0.1:
  date: 2019-09-01
  Added:
    utils:
      - The `measurementDiffers` method is new.
    models:
      - Expanded the size ranges available.
      - Added the `withBreasts` models which were missing in earlier releases.
  Changed:
    models:
      - The models data is now based on the data from the `neckstimate` method in the utils package.
  Fixed:
    theo:
      - "[#78](https://github.com/freesewing/freesewing/issues/78):
        Removed inherited notches from fly shield and side piece."
    models:
      - "[#86](https://github.com/freesewing/freesewing/issues/86):
        The `seatCircumference` measurement was missing, thus making it unavailable on the website"

