[build]
  base = "packages/freesewing.dev"
  publish = "out/"
  command = "yarn export"

# Production website (freesewing.dev)
# Not yet implemented

# Pre-release website (canary.freesewing.dev)
[context.canary]
  command = "yarn export"
  [context.canary.environment]
    SITE = "dev"

