name: Sync Dependabot Bump
on:
  pull_request:
    types: [opened, reopened, edited]


jobs:
  sync:
    name: Sync dependency files
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Sync Script
        run: node ./scripts/sync-dependencies.mjs ${{ github.head_ref }}
      - name: Commit Changes
        run: |
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "[dependabot skip] bumped ${{ github.head_ref }} changes in config/dependencies.yaml"
          git push
