# In the event that lint is broken in mainline (e.g. `develop`, the only mainline branch that has linting code right now),
# this workflow is expected to pass even if lint.all.yml fails.

name: ESLint Changed Files

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npx lerna bootstrap
        env:
          CI: true
      - name: Build all
        run: npm run buildall
      - name: Run eslint
        run: npx eslint --no-error-on-unmatched-pattern $(git diff --name-only $GITHUB_BASE_REF)
