name: Unit tests - Plugintest

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/plugintest/**'
      - '!packages/plugintest/README.md'
  pull_request:
    branches:
      - develop
    paths:
      - 'packages/plugintest/**'
      - '!packages/plugintest/README.md'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: cd packages/plugintest && npm install
        env:
          CI: true
      - name: Install peer & test dependencies
        run: "cd packages/plugintest && npm install @freesewing/core@^2.20.4 @freesewing/plugin-bundle@^2.20.4 @freesewing/plugin-banner@^2.20.4 @freesewing/plugin-bartack@^2.20.4 @freesewing/plugin-bust@^2.20.4 @freesewing/plugin-buttons@^2.20.4 @freesewing/plugin-cutonfold@^2.20.4 @freesewing/plugin-dimension@^2.20.4 @freesewing/plugin-flip@^2.20.4 @freesewing/plugin-gore@^2.20.4 @freesewing/plugin-grainline@^2.20.4 @freesewing/plugin-i18n@^2.20.4 @freesewing/plugin-logo@^2.20.4 @freesewing/plugin-measurements@^2.20.4 @freesewing/plugin-mirror@^2.20.4 @freesewing/plugin-notches@^2.20.4 @freesewing/plugin-round@^2.20.4 @freesewing/plugin-scalebox@^2.20.4 @freesewing/plugin-sprinkle@^2.20.4 @freesewing/plugin-svgattr@^2.20.4 @freesewing/plugin-theme@^2.20.4 @freesewing/plugin-title@^2.20.4 @freesewing/plugin-validate@^2.20.4 @freesewing/models@2.20.4 @freesewing/pattern-info@2.20.4 mocha chai"
        env:
          CI: true
      - name: Build pattern
        run: cd packages/plugintest && npm run build
      - name: Run pattern unit tests
        run: cd packages/plugintest && npm run testci
