name: Unit tests - Simone

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: cd packages/simone && npm install
        env:
          CI: true
      - name: Install peer & test dependencies
        run: 'cd packages/simone && npm install @freesewing/core@^2.7.0-beta.3 @freesewing/plugin-bundle@^2.7.0-beta.3 @freesewing/brian@^2.7.0-beta.3 @freesewing/simon@^2.7.0-beta.3 @freesewing/plugin-buttons@^2.7.0-beta.3 @freesewing/plugin-flip@^2.7.0-beta.3 @freesewing/plugin-bust@^2.7.0-beta.3 @freesewing/models@2.7.0-beta.3 @freesewing/pattern-info@2.7.0-beta.3 mocha chai'
        env:
          CI: true
      - name: Build pattern
        run: cd packages/simone && npm run build
      - name: Run pattern unit tests
        run: cd packages/simone && npm run testci
