name: All Tests

on:
  push:
    branches:
      - develop
      - v2
    paths:
      - '**'
      - '!**/*.md'
  pull_request:
    branches:
      - develop
      - v2
    paths:
      - '**'
      - '!**/*.md'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npx lerna bootstrap
        env:
          CI: true
      - name: Build all
        run: npm run buildall
      - name: Run all tests
        run: npm run testall
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/core/coverage/coverage-final.json
          flags: core
          name: codecov-core
          fail_ci_if_error: true
