name: Unit tests - Carlita

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/carlita/**'
      - '!packages/carlita/README.md'
  pull_request:
    branches:
      - develop
    paths:
      - 'packages/carlita/**'
      - '!packages/carlita/README.md'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: cd packages/carlita && npm install
        env:
          CI: true
      - name: Install peer & test dependencies
        run: "cd packages/carlita && npm install @freesewing/core@^2.20.6 @freesewing/plugin-bundle@^2.20.6 @freesewing/brian@^2.20.6 @freesewing/bent@^2.20.6 @freesewing/carlton@^2.20.6 @freesewing/plugin-bust@^2.20.6 @freesewing/plugin-buttons@^2.20.6 @freesewing/plugin-mirror@^2.20.6 @freesewing/models@2.20.6 @freesewing/pattern-info@2.20.6 mocha chai"
        env:
          CI: true
      - name: Build pattern
        run: cd packages/carlita && npm run build
      - name: Run pattern unit tests
        run: cd packages/carlita && npm run testci
