name: Test new-design
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template:
          - scratch
          - tutorial
          - bent
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install --workspaces=false
      working-directory: ./packages/new-design
    - name: Prebuild i18n
      run: yarn i18n-only
      working-directory: ./packages/new-design
    - name: Generate Design
      run: |
        cd ../
        TEMPLATE=${{ matrix.template }} NAME=test${{ matrix.template }} node ${{ github.workspace }}/packages/new-design/scripts/generate-from-cli.mjs
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
      working-directory: ../test${{ matrix.template }}
    - name: Run Playwright tests
      run: yarn playwright test
      working-directory: ../test${{ matrix.template }}
