name: Unit tests - Wahid

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/wahid/**'
      - '!packages/wahid/README.md'
  pull_request:
    branches:
      - develop
    paths:
      - 'packages/wahid/**'
      - '!packages/wahid/README.md'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: cd packages/wahid && npm install
        env:
          CI: true
      - name: Install peer & test dependencies
        run: "cd packages/wahid && npm install @freesewing/core@^2.20.2 @freesewing/plugin-bundle@^2.20.2 @freesewing/brian@^2.20.2 @freesewing/plugin-buttons@^2.20.2 @freesewing/plugin-round@^2.20.2 @freesewing/models@2.20.2 @freesewing/pattern-info@2.20.2 mocha chai"
        env:
          CI: true
      - name: Build pattern
        run: cd packages/wahid && npm run build
      - name: Run pattern unit tests
        run: cd packages/wahid && npm run testci
